#!/usr/bin/env python3
"""
HackerNews Digest - Daily summary of top HN stories
"""

import json
import urllib.request
from datetime import datetime

def fetch_hn_top(count=15):
    """Get top HN stories"""
    try:
        url = "https://hacker-news.firebaseio.com/v0/topstories.json"
        req = urllib.request.Request(url, headers={'User-Agent': 'HNDigest/1.0'})
        with urllib.request.urlopen(req, timeout=10) as resp:
            top_ids = json.loads(resp.read())[:count]
        
        stories = []
        for story_id in top_ids:
            story_url = f"https://hacker-news.firebaseio.com/v0/item/{story_id}.json"
            req = urllib.request.Request(story_url, headers={'User-Agent': 'HNDigest/1.0'})
            with urllib.request.urlopen(req, timeout=10) as resp:
                story = json.loads(resp.read())
                if story.get('title'):
                    stories.append({
                        'title': story.get('title', ''),
                        'url': story.get('url', ''),
                        'score': story.get('score', 0),
                        'comments': story.get('descendants', 0),
                        'by': story.get('by', 'unknown'),
                        'time': datetime.fromtimestamp(story.get('time', 0)).strftime('%H:%M')
                    })
        return stories
    except:
        return []

def generate_digest():
    print("=" * 60)
    print("📰 HACKERNEWS DAILY DIGEST")
    print(f"   {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}")
    print("=" * 60)
    
    print("\n📥 Fetching top HN stories...")
    stories = fetch_hn_top(20)
    print(f"   ✅ Got {len(stories)} stories")
    
    # Sort by score
    stories.sort(key=lambda x: x['score'], reverse=True)
    
    # Print digest
    print("\n" + "=" * 60)
    print("🔥 TOP 10 STORIES")
    print("=" * 60)
    
    for i, story in enumerate(stories[:10], 1):
        title = story['title'][:65]
        score = story['score']
        comments = story['comments']
        
        print(f"\n{i}. {title}...")
        print(f"   📈 {score} pts | 💬 {comments} comments | 👤 {story['by']}")
        
        if story['url']:
            domain = story['url'].split('/')[2] if '://' in story['url'] else story['url']
            print(f"   🔗 {domain}")
    
    # Categories
    print("\n" + "=" * 60)
    print("📊 SCORE DISTRIBUTION")
    print("=" * 60)
    
    scores = [s['score'] for s in stories]
    avg = sum(scores) / len(scores) if scores else 0
    max_score = max(scores) if scores else 0
    min_score = min(scores) if scores else 0
    
    print(f"   Average: {avg:.0f} pts")
    print(f"   Highest: {max_score} pts")
    print(f"   Lowest: {min_score} pts")
    
    # Top commenters (by count of top stories)
    print("\n" + "=" * 60)
    print("👥 TOP COMMENTERS (in top 20)")
    print("=" * 60)
    
    from collections import Counter
    commenters = Counter(s['by'] for s in stories[:20])
    for author, count in commenters.most_common(5):
        print(f"   {author}: {count} stories")
    
    # Save
    result = {
        'timestamp': datetime.now().isoformat(),
        'stories': stories[:20],
        'stats': {
            'avg_score': avg,
            'max_score': max_score,
            'min_score': min_score
        }
    }
    
    with open('/output/hn_digest.json', 'w') as f:
        json.dump(result, f, indent=2)
    
    # Generate markdown digest
    md = f"""# 📰 HackerNews Daily Digest

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}

## Top 10 Stories

"""
    for i, story in enumerate(stories[:10], 1):
        md += f"{i}. **{story['title']}**\n"
        md += f"   - 📈 {story['score']} pts | 💬 {story['comments']} comments\n"
        if story['url']:
            md += f"   - 🔗 {story['url']}\n"
        md += "\n"
    
    md += f"""
## Stats
- Average score: {avg:.0f}
- Highest: {max_score}
- Lowest: {min_score}

---
*Generated by Arlo's HN Digest*
"""
    
    with open('/output/hn_digest.md', 'w') as f:
        f.write(md)
    
    print("\n" + "=" * 60)
    print("✅ Saved to /output/hn_digest.json and .md")
    print("=" * 60)
    
    return result

if __name__ == "__main__":
    generate_digest()